### ISSUE TITLE
bliss-audio 0.6.3 not available?

### ISSUE THREAD

**Issue by chrober** [Polochon-street/bliss-rs#51]
Hi,

I am usually building bliss-analyser (https://github.com/CDrummond/bliss-analyser) on a piCorePlayer (Raspberry Pi 4B).
A couple of days ago bliss-analyser switched to bliss-audio 0.6.3 and now building bliss-analyser fails with the following error
```
    Updating crates.io index
error: failed to select a version for the requirement `bliss-audio = "^0.6.3"`
candidate versions found which didn't match: 0.6.1, 0.6.0, 0.5.3, ...
location searched: crates.io index
required by package `bliss-analyser v0.2.2 (/mnt/mmcblk0p2/bliss-analyzer/src)`
```

Deleting and re-populating the cargo registry did not help. And anyway, when checking the cargo registry I do find entries for 0.6.3 and 0.6.4 in ``registry/index/github.com-1ecc6299db9ec823/.cache/bl/is/bliss-audio``

Not sure if this is a problem in bliss-rs, bliss-analyser, or my build environment... does anybody have some hints? Please?

Best regards,
Christoph

**Comment by toofar** [comment]
What cargo version are you on? I had this issue with blissify too, not being able to find bliss-audio 0.6.4. I'm on cargo 1.56.0 (thanks debian) and I suspect it is this issue: https://github.com/rust-lang/cargo/issues/11009
I ended up checking out bliss-rs and changing the Cargo.toml file to point to my local checkout. Installing cargo some non-distribution way would probably be a more robust solution.

**Comment by chrober** [comment]
Thank you @toofar for your reply!
> What cargo version are you on?

`cargo --version` reports the following:
```
cargo 1.59.0
```
I will check work-around possibilities later next week.

**Comment by chrober** [comment]
After a while I was finally diving into this again.
As suggested by @toofar I also tried to use a local checkout of bliss-rs in Cargo.toml.
However, this gives me the following error when trying to build bliss-analyser: 
```
error: failed to get `bliss-audio` as a dependency of package `bliss-analyser v0.2.2 (/mnt/mmcblk0p2/bliss-analyzer/src)`

Caused by:
  failed to load source for dependency `bliss-audio`

Caused by:
  Unable to update /mnt/mmcblk0p2/bliss-rs/src

Caused by:
  failed to parse manifest at `/mnt/mmcblk0p2/bliss-rs/src/Cargo.toml`

Caused by:
  namespaced features with the `dep:` prefix are only allowed on the nightly channel and requires the `-Z namespaced-features` flag on the command-line
```
I don't use nightly channel versions of cargo or rustc. Would this also be necessary for using bliss-rs from crates.io?

**Comment by Polochon-street** [comment]
hi!
Finally looking into this after some time - @chrober what does `rustuc --version` say? I suspect your rustc version is a bit too old, so it thinks some syntax we use in `Cargo.toml` is nightly only (but by now it's been stabilized so it's available without nightly)
If you use rustup, using `rustup update` and trying to build again should work :)

**Comment by chroberino** [comment]
> hi! Finally looking into this after some time - @chrober what does `rustuc --version` say? I suspect your rustc version is a bit too old, so it thinks some syntax we use in `Cargo.toml` is nightly only (but by now it's been stabilized so it's available without nightly) If you use rustup, using `rustup update` and trying to build again should work :)

Hi and sorry for the late reply. The rust version I have at hand is 1.59.0. I will try to upgrade.

**Comment by Polochon-street** [comment]
Hi! Just as a side-note, if you're unable to update bliss-rs - I think checking out a local copy and editing these lines https://github.com/Polochon-street/bliss-rs/blob/master/Cargo.toml#L32-L37 (the "library" and "serde" features) in `Cargo.toml` might do the trick.
Let me know if this worked!

**Comment by chroberino** [comment]
> Let me know if this worked!

Thanks for the hint, I am fine with that now!

**Comment by Polochon-street** [comment]
awesome! Closing then :)
