### ISSUE TITLE
Python bindings for arm64?

### ISSUE THREAD

**Issue by jhurliman** [Polochon-street/bliss-rs#57]
Looking at <https://pypi.org/project/bliss-audio/#files> it seems that only x86_64 binaries have been released on PyPi. Could arm64 builds be distributed as well?

Apologies if this is not the correct repo for the Python bindings, it's not clear where the source code to the `bliss-audio` Python library lives.

**Comment by Polochon-street** [comment]
Hi,

You're in the correct repo - these bindings are "unofficial" things I did on my spare time using [maturin](https://github.com/PyO3/maturin/).
However, binaries should be doable for arm64, I'd just need to get in shape with maturin :)

**Comment by Polochon-street** [comment]
Hi,

I've finally gotten around to look at this, and managed to get something to compile.

Could you try to install it / play around, before I submit it to PyPi?

Downloading http://polochon.lelele.io/bliss_audio-0.1.7-cp38-abi3-manylinux_2_31_aarch64.whl, and running `pip install bliss_audio-0.1.7-cp38-abi3-manylinux_2_31_aarch64.whl` should be enough.
Then, it's all good if  `python -c 'from bliss_audio import Song; print(Song("/path/to/a/valid/song).analysis)'` prints some numbers.

**Comment by Polochon-street** [comment]
Update: managed to get an arm64 VM working, and everything seems to work. `pip install bliss_audio` on an arm64 should be working now :)

Closing. Don't hesitate to reopen if you have any other issues though.
