### ISSUE TITLE
Idea: split analysis into separate library

### ISSUE THREAD

**Issue by jprjr** [Polochon-street/bliss-rs#63]
Hi there -

I was looking at this library, and was curious about how to perform analysis on audio samples from some other source, as far as I can tell it's a requirement to have bliss perform decoding and analysis.

Would it make sense to split the analysis part off into a separate library? That could potentially be a smaller lib since it wouldn't require decoding, cuesheet parsing, etc, though the main benefit would be the ability to use other audio decoders

**Comment by jprjr** [comment]
That would be very useful!

**Comment by Polochon-street** [comment]
I just updated the main branch with https://github.com/Polochon-street/bliss-rs/commit/b4ca23a0b627420018b1040ddb53d36ee1d00245, that makes `analyze` public.
Depending on your version of ffmpeg, you might or might not be able to compile it - rust-ffmpeg for ffmpeg 6.1 is currently being worked on, so bliss is currently not working with ffmpeg 6.1.

**Comment by jprjr** [comment]
That was actually part of why I was suggesting splitting it out for use with other decoders to be honest. I was able to work around it by compiling ffmpeg 6.0 and setting the PKG_CONFIG_PATH variable appropriately

**Comment by Polochon-street** [comment]
That makes sense. Maybe making an `ffmpeg` compilation flag that is turned on by default, but could be turned off would make your life easier then?

**Comment by jprjr** [comment]
That could work too! Though once that's disabled, I presume that's getting close to the original idea of having Analysis split out?

Basically I've got code for library management already, code for decoding already, tag parsing, and so on. Having an API like "give this function a bunch of float32 samples, mono, at a sample rate of 22050Hz, get some analysis back" is the main thing I'm interested in, for my use case.

**Comment by Polochon-street** [comment]
That's what it should do, yes :)

Perhaps you could try cloning `master` and telling me if `Song::analyze()` works as expected for you? Then I'll add a flag so you can disable ffmpeg during compilation.

**Comment by jprjr** [comment]
Looks like that works! Wrote a short program, created a mono WAV file with float32 samples and a 22050Hz sample rate, and got the same results:

```rust
use bliss_audio::Song;
use hound;
use std::env;

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    for path in &args {

        let mut reader = hound::WavReader::open(path).unwrap();
        let samples: Vec<f32> = reader.samples::<f32>().flatten().collect();
        let analysis = Song::analyze(&samples).unwrap();
        println!("Song::analyze: {:?}",analysis);

        let song = Song::from_path(path).unwrap();
        println!("song.analysis: {:?}", song.analysis);
    }
}
```

**Comment by Polochon-street** [comment]
Perfect, thanks :)
I'll work on that, should be able to push something this week.
Cheers!

**Comment by Polochon-street** [comment]
Hi @jprjr!

Took me more time than expected, but I started making a `disable-ffmpeg` optional feature [here](https://github.com/Polochon-street/bliss-rs/pull/65) (`make-ffmpeg-optional`branch).

I still need to polish it a little bit, but could you check if it would fit your use-case?

**Comment by jprjr** [comment]
Hi there! Sorry for the delay

So, I'm still really new to rust and Cargo so my Cargo.toml may just be wrong? Here's what I setup:

```Cargo.toml
[package]
name = "bliss_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"

[dependencies.bliss-audio]
git = "https://github.com/Polochon-street/bliss-rs.git"
branch = "make-ffmpeg-optional"
default-features = false
features = ["disable-ffmpeg"]
```

And my main.rs file, where I decode audio with another library:

```rust
use bliss_audio::Song;
use hound;
use std::env;

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    for path in &args {

        let mut reader = hound::WavReader::open(path).unwrap();
        let samples: Vec<f32> = reader.samples::<f32>().flatten().collect();
        let analysis = Song::analyze(&samples).unwrap();
        println!("Song::analyze: {:?}",analysis);
    }
}
```

It builds and works, but from the log output I think it still pulled in the ffmpeg dependencies, they're still linked to the final binary:

```bash
 objdump -p target/debug/bliss_demo | grep NEEDED
  NEEDED               libavutil.so.58
  NEEDED               libavformat.so.60
  NEEDED               libavfilter.so.9
  NEEDED               libavdevice.so.60
  NEEDED               libswscale.so.7
  NEEDED               libswresample.so.4
  NEEDED               libavcodec.so.60
  NEEDED               libgcc_s.so.1
  NEEDED               libm.so.6
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
```

So, it seems like the feature flag disables compiling functions that require ffmpeg, but it doesn't remove the overall ffmpeg dependencies, so they still get linked in, and I think building on a system without ffmpeg (or if ffmpeg-next/ffmpeg-sys-next are just out of date), building would fail

**Comment by Polochon-street** [comment]
hi!

I've revamped the branch a little bit, so now by default the `ffmpeg` feature is enabled, and to disable it, you need to disable that feature.

I think that your example is correct, and changing the Cargo.toml to reflect the changes should work like this:

```
[package]
name = "bliss_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"

[dependencies.bliss-audio]
git = "https://github.com/Polochon-street/bliss-rs.git"
branch = "make-ffmpeg-optional"
default-features = false
features = ["bliss-audio-aubio-rs/static"]
```

if this works for you, I'll do some cleanup and merge it. I plan on making `from_path` something anyone can implement, so you could easily implement your own decoder, and then just use all of bliss' other examples seamlessly, but that will take a bit more time :)

**Comment by jprjr** [comment]
Looks like I get an error with that Cargo.toml:

```
error: failed to parse manifest at `/home/john/Repos/jprjr/bliss_demo/Cargo.toml`

Caused by:
  feature `bliss-audio-aubio-rs/static` in dependency `bliss-audio` is not allowed to contain slashes
  If you want to enable features of a transitive dependency, the direct dependency needs to re-export those features from the `[features]` table.
````

**Comment by Polochon-street** [comment]
I just changed some things, I think if you try this one
```
[package]
name = "bliss_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
hound = "3.5.1"

[dependencies.bliss-audio]
git = "https://github.com/Polochon-street/bliss-rs.git"
branch = "make-ffmpeg-optional"
default-features = false
features = ["aubio-static"]
```

**Comment by jprjr** [comment]
Confirmed, that worked! Looks like the final binary isn't linked with ffmpeg libraries at all.

```bash
objdump -p target/debug/bliss_demo | grep NEEDED
  NEEDED               libc.so.6
  NEEDED               ld-linux-x86-64.so.2
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
```

**Comment by Polochon-street** [comment]
Hi @jprjr!

It took some work, but ffmpeg is finally an optional dependency of bliss. Compiling with `cargo build --release --no-default-features` should give you bliss without ffmpeg :)

I made an entire `decoder` module (https://docs.rs/bliss-audio/latest/bliss_audio/decoder/index.html) in case people also want to implement their own decoders.

Tell me if that works for you!

**Comment by Polochon-street** [comment]
closing this since it's been some time since last activity - feel free to reopen if needed.
